import {manrope, poppins, roboto} from '@/app/fonts';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import '@/assets/css/style.css';
import '@/assets/scss/style.scss';
import FooterTerpenes from '@/components/Footer/FooterTerpenes';
import HeaderTerpenes from '@/components/Header/HeaderTerpenes';
import {getCategories} from '@/services/getCategories';
import ReduxProvider from '@/store/ReduxProvider';
import {cookies} from 'next/headers';
import {Toaster} from 'react-hot-toast'; // Import react-hot-toast

export const metadata = {
  title: 'Medical Terpenes',
  description: 'Generated by create next app',
};

export default async function RootLayout({children}) {
  const categoriesData = await getCategories();

  const authToken = cookies()?.get('authToken');
  const isLoggedIn = authToken ? !!authToken.value : false;

  return (
    <html lang='en'>
    <body className={`${roboto.variable} ${poppins.variable} ${manrope.variable}`}>
    <ReduxProvider>
      <HeaderTerpenes categoryList={categoriesData?.data?.categories} isLoggedIn={isLoggedIn}/>
      {/* React Hot Toast Toaster for global notifications */}
      <Toaster position="bottom-left" reverseOrder={false}/>
      {children}
      <FooterTerpenes/>
    </ReduxProvider>
    </body>
    </html>
  );
}
